### PR TITLE
Fuad Reza Pahlevi Profile Card Added

### PR DESCRIPTION
**Pull request by fuadreza**

### CODE REVIEW

**Comment by fuadreza** [comment]
Emmm.. Can my pull request get label for hacktober accepted? thanks.

**Comment by fuadreza** [comment]
@imKashyap how can i get label for hacktober-accepted ?

**Comment by imKashyap** [comment]
@fuadreza Hacktoberfest updated their rules for PR submissions on 3rd of october. Every PR sent before October 3 are considered valid even if the `hacktoberfest-accepted` tag is not added. But for the PRs made later need to be added with the tag. 

Therefore, you have already qualified for hacktoberfest-accepted PR submission even without the tag. Your PR must be in the review period . Alright?

**Comment by fuadreza** [comment]
@imKashyap Oh Okay, I see. From now, my PR Submission is In Review status. Thank you for the explanation, I just new to open source project outside my own repo 😄

**Pull request merged**
